Feature/update requirements with hashes
ONSdigital/sdx-receipt-rrm pull request #46
Opened 2017-08-14 12:03 UTC by gemmai95

## What? and Why?
> What does this pull request change/fix? Why was it nessessary?

Adds hashes for each requirement this should help avoid accidental or malicious changes.

## Checklist
  - [x] CHANGELOG.md updated? (if required)

2017-08-15 07:31 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Turn on PIP hashed requirements.txt (3)](https://trello.com/c/ZBaaoggQ/246-turn-on-pip-hashed-requirementstxt-3)

2017-08-15 11:11 UTC, necrophonic submitted a review, later dismissed

2017-08-15 11:11 UTC, necrophonic commented on CHANGELOG.md
> +  - Update requirements to include hashes
See comment on [sdx-rabbit-monitor](https://github.com/ONSdigital/sdx-rabbit-monitor/pull/29/files/c5002976f8e11a3b83c47a3304ce88dfecf8421f)

2017-08-15 13:16 UTC, tej99 requested changes
"--require-hashes" missing from make file

2017-08-16 06:43 UTC, tej99 submitted a review, later dismissed

2017-08-17 08:18 UTC, JamesGardiner requested changes

2017-08-17 08:18 UTC, JamesGardiner commented on Makefile
>  	git clone -b 0.7.0 https://github.com/ONSdigital/sdx-common.git
Refs to sdx-common need to be removed

2017-08-17 14:50 UTC, gemmai95 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Turn on PIP hashed requirements.txt (3)](https://trello.com/c/ZBaaoggQ/246-turn-on-pip-hashed-requirementstxt-3)

2017-08-18 13:47 UTC, JamesGardiner approved these changes

2017-08-18 13:47 UTC, merged