Tagging for release 2.15.1
ONSdigital/sdx-receipt-rrm pull request #85
Opened 2019-03-14 11:09 UTC by mfcrocker

## What? and Why?
This is the pull request ready for release 2.15.1

## Checklist
  - [x] CHANGELOG.md updated? (if required)

2019-03-14 11:33 UTC, insacuri commented on CHANGELOG.md
> +### 2.15.1 2019-03-14
It's really noddy but can you add a new `### Unreleased` line 2 lines above this?

2019-03-14 11:34 UTC, insacuri requested changes
see comment

2019-03-18 10:15 UTC, insacuri approved these changes

2019-03-18 10:19 UTC, ryangrundy7 approved these changes

2019-03-18 10:21 UTC, merged